"""Orphan cleanup service.

Detects and deletes Canvas wiki pages that were left behind by killed
or partially-completed AutoRemedy runs. The most common case is
CLU-67's textbook chapter pages — when AutoRemedy phase 4 is killed
mid-conversion (e.g., by a deploy), the chapter wiki pages already
created in Canvas remain as orphans (unpublished, unlinked, contributing
to PopeTech alert counts on subsequent scans).

Generic enough to be reused for any "named-with-suffix" cleanup
pattern. Currently matches:
  - "{filename} - Pages N-M"   (CLU-67 fixed-split fallback)
  - "{filename} - Chapter N: {title}"  (CLU-67 heading-detected split)
"""
from __future__ import annotations

import re
from typing import Any

import structlog

_logger = structlog.get_logger(__name__)


# Title patterns generated by CLU-67 chapter splitting:
#   "Some Filename - Pages 1-20"
#   "Some Filename - Pages 281-300"
_PAGES_RANGE_RE = re.compile(r"^.+\s-\sPages\s\d+-\d+$")

# Heading-detected chapter pattern:
#   "Some Filename - Chapter 1: Introduction"
#   "Some Filename - Chapter 12: Conclusion"
_CHAPTER_NAMED_RE = re.compile(r"^.+\s-\sChapter\s\d+(:.*)?$")


def is_orphan_chapter_title(title: str) -> bool:
    """Return True if the title matches a CLU-67 chapter page pattern."""
    if not title:
        return False
    return bool(_PAGES_RANGE_RE.match(title) or _CHAPTER_NAMED_RE.match(title))


class OrphanCleanupService:
    """Find and delete orphan wiki pages from killed AutoRemedy runs.

    Keeps the Canvas client out of the constructor so the same service
    instance can serve multiple courses with different sessions.
    """

    async def find_orphan_pages(
        self,
        canvas_client: Any,
        course_id: int,
    ) -> list[dict]:
        """Return Canvas page summaries for pages whose title matches
        an orphan-chapter pattern. Doesn't delete anything — just lists
        candidates for confirmation."""
        orphans: list[dict] = []
        async for page in canvas_client.get_paginated(
            f"/api/v1/courses/{course_id}/pages",
        ):
            title = page.get("title") or ""
            if is_orphan_chapter_title(title):
                orphans.append(page)
        _logger.info(
            "orphan_cleanup_found",
            course_id=course_id,
            count=len(orphans),
        )
        return orphans

    async def delete_pages(
        self,
        canvas_client: Any,
        course_id: int,
        page_urls: list[str],
    ) -> int:
        """Delete the given wiki pages by URL slug. Returns the count
        of successfully deleted pages. Failures are logged but don't
        abort the operation — best effort across the whole list."""
        deleted = 0
        for slug in page_urls:
            try:
                await canvas_client.delete(
                    f"/api/v1/courses/{course_id}/pages/{slug}"
                )
                deleted += 1
                _logger.info(
                    "orphan_cleanup_deleted",
                    course_id=course_id,
                    slug=slug,
                )
            except Exception as exc:
                _logger.warning(
                    "orphan_cleanup_delete_failed",
                    course_id=course_id,
                    slug=slug,
                    error=str(exc),
                )
        return deleted
