import { useState, useEffect } from 'react'
import { useParams, Link } from 'react-router-dom'
import { useLTI } from '@/contexts/LTIContext'
import { Card, Badge } from '@/components/ui'
import { CheckCircle2, FileText, ArrowLeft } from 'lucide-react'
import { getPreviews, type PreviewSummary } from '@/api/client'

// Human-readable rule descriptions
const RULE_LABELS: Record<string, string> = {
  IMG001: 'Added missing alt text',
  IMG002: 'Replaced filename-based alt text',
  IMG003: 'Differentiated duplicate alt text',
  IMG004: 'Shortened overly long alt text',
  TBL001: 'Added table header scope',
  TBL002: 'Added table caption',
  HDG001: 'Fixed heading hierarchy',
  HDG002: 'Added missing heading text',
  LNK001: 'Improved non-descriptive link text',
  LNK005: 'Fixed raw URL link text',
  STR001: 'Cleaned up empty elements',
  MDA001: 'Added iframe title',
}

function describeRules(rules: string[]): string[] {
  const unique = [...new Set(rules)]
  return unique.map((r) => RULE_LABELS[r] || r).slice(0, 5)
}

export function ChangesPage() {
  const { jobId } = useParams<{ jobId: string }>()
  const { session } = useLTI()
  const [previews, setPreviews] = useState<PreviewSummary[]>([])
  const [loading, setLoading] = useState(true)

  const courseId = session?.canvasCourseId

  useEffect(() => {
    if (!courseId || !jobId) return
    setLoading(true)
    getPreviews(courseId, jobId)
      .then((data) => setPreviews(data.previews))
      .catch(() => setPreviews([]))
      .finally(() => setLoading(false))
  }, [courseId, jobId])

  const totalIssues = previews.reduce((sum, p) => sum + p.issues_fixed_count, 0)
  const totalAltTexts = previews.reduce((sum, p) => sum + p.alt_texts_count, 0)

  return (
    <div>
      {/* Back link */}
      <Link
        to="/autoremedy"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-brand-primary hover:underline"
      >
        <ArrowLeft className="h-4 w-4" aria-hidden="true" />
        Back to AutoRemedy
      </Link>

      {/* Summary header */}
      <Card className="mb-6">
        <div className="flex items-center gap-3">
          <CheckCircle2 className="h-8 w-8 text-green-500 shrink-0" aria-hidden="true" />
          <div>
            <h2 className="text-lg font-bold text-text">Changes Applied to Canvas</h2>
            <p className="text-sm text-text-subtle">
              {totalIssues} fixes applied across {previews.length} pages
              {totalAltTexts > 0 && ` — ${totalAltTexts} alt texts generated by AI`}
            </p>
          </div>
        </div>
      </Card>

      {/* Per-page list */}
      {loading ? (
        <Card className="py-12 text-center">
          <div
            className="mx-auto h-8 w-8 animate-spin rounded-full border-2 border-brand-primary border-t-transparent"
            role="status"
            aria-label="Loading changes"
          />
        </Card>
      ) : previews.length === 0 ? (
        <Card className="py-8 text-center text-text-subtle">
          No change details available for this run.
        </Card>
      ) : (
        <div className="space-y-3">
          {previews.map((p) => (
            <Card key={p.page_id} className="flex items-start gap-3">
              <FileText className="h-5 w-5 text-text-subtle mt-0.5 shrink-0" aria-hidden="true" />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  <h3 className="font-medium text-text truncate">{p.page_title}</h3>
                  <Badge variant="success">{p.issues_fixed_count} fixed</Badge>
                  {p.alt_texts_count > 0 && (
                    <Badge variant="info">{p.alt_texts_count} alt text{p.alt_texts_count !== 1 ? 's' : ''}</Badge>
                  )}
                </div>
                <div className="mt-1 flex flex-wrap gap-1.5">
                  {describeRules(p.issues_fixed).map((desc, i) => (
                    <span key={i} className="text-xs text-green-700 bg-green-50 px-2 py-0.5 rounded-full">
                      {desc}
                    </span>
                  ))}
                </div>
              </div>
              <span className="text-xs text-green-600 font-medium whitespace-nowrap">Applied</span>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
